/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BirthdayPicker: typeof import('./src/components/BirthdayPicker.vue')['default']
    FillCalendar: typeof import('./src/components/calendars/fill-calendar/FillCalendar.vue')['default']
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    NumberInput: typeof import('./src/components/NumberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./src/components/SelectInput.vue')['default']
    SquareCalendar: typeof import('./src/components/calendars/square-calendar/SquareCalendar.vue')['default']
    TimerCalendar: typeof import('./src/components/calendars/timer-calendar/TimerCalendar.vue')['default']
  }
}
